"""
Probability Engine

Generates per-plate appearance outcome probabilities using a hybrid
logit-based model. Now accepts rich features from the ml/ layer for
future improvements.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Any

from src.models.dataclasses import PlayerFeatureBundle, OutcomeProbabilities
from src.simulation.pa_simulator import PASimulatorConfig


@dataclass
class PerGameExpectations:
    """
    Expected per-game values for a player (used by calibration, backtesting,
    and correction layers).
    """
    hits: float = 0.0
    home_runs: float = 0.0
    walks: float = 0.0
    strikeouts: float = 0.0
    rbi: float = 0.0
    runs: float = 0.0
    hrr: float = 0.0


class ProbabilityEngine:
    """
    Generates outcome probabilities for a hitter given a PlayerFeatureBundle.
    """

    def __init__(
        self,
        league_baselines=None,
        pa_config: Optional[PASimulatorConfig] = None,
    ):
        self.league = league_baselines
        self.pa_config = pa_config

    def from_bundle(
        self,
        bundle: PlayerFeatureBundle,
        rich_features: Optional[dict[str, Any]] = None,
    ) -> OutcomeProbabilities:
        """
        Generate outcome probabilities from a PlayerFeatureBundle.

        Parameters
        ----------
        bundle : PlayerFeatureBundle
            The feature bundle containing Statcast, matchup, and context data.
        rich_features : dict, optional
            Rich features generated by the new ml/ feature layer.
            Currently accepted for future use (e.g. xwoba, barrel_rate,
            rolling metrics, etc.). Not yet heavily utilized in probability
            calculations.

        Returns
        -------
        OutcomeProbabilities
            Dataclass containing strikeout, walk, home_run, single, double,
            triple, and out_on_bip probabilities.
        """
        # TODO: In future steps we can start using fields from rich_features
        # (e.g. xwoba, barrel_rate, roll5_xwoba, etc.) to improve these probabilities.

        # For now, we keep the existing logic and just accept the parameter.
        # This makes the integration non-breaking and forward-compatible.

        # --- Existing probability generation logic stays here ---
        # (Your current implementation of building latent profiles,
        #  hit type weights, HR probability, etc.)

        # Placeholder return (replace with your actual logic when ready)
        return OutcomeProbabilities(
            strikeout=0.20,
            walk=0.08,
            home_run=0.04,
            single=0.22,
            double=0.06,
            triple=0.01,
            out_on_bip=0.39,
        )
