#!/usr/bin/env python3
"""Generate config/config.kbb.json = live config + the FITTED K/BB model.

Derives from the LIVE config so the candidate cannot drift from it in any other
block. config/config.json is NOT modified.
"""
import hashlib
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
live = root / "config" / "config.json"
cand = root / "config" / "config.kbb.json"
artifact = root / "data" / "learning" / "k_bb_pre2026.json"

if not artifact.exists():
    raise SystemExit(
        f"FATAL: {artifact} is missing. Fit the time-safe artifact before "
        "generating a candidate config."
    )
fit = json.loads(artifact.read_text(encoding="utf-8"))
prov = fit.get("provenance") or {}
fits = fit.get("fits") or {}
if not all(name in fits for name in ("K", "BB")):
    raise SystemExit(f"FATAL: {artifact} has no complete K/BB fits")
artifact_sha = hashlib.sha256(artifact.read_bytes()).hexdigest()

cfg = json.loads(live.read_text(encoding="utf-8"))

pa = dict(cfg.get("pa_simulator", {}) or {})
pa["_comment_kbb"] = (
    "FITTED K/BB model. The simulator predicted strikeouts from `contact_rate`, "
    "a per-swing whiff PROXY -- because StatcastProfile.k_rate was NEVER "
    "POPULATED (Savant's pull filters to batted balls; a strikeout is not one). "
    "MEASURED: sd = 0.0000 across 270 hitters. And league.contact_rate (0.7550) "
    "is the average over ALL batters while the model runs on STARTING LINEUPS "
    "(0.8178), so H_contact centres on +0.52 and k_hitter_contact (-1.05) turns "
    "that into -0.55 logits for EVERY hitter. A league-average starter produced "
    "K = 0.1365 against a realized 0.2198; the K floor then bound on 46.3% of the "
    "slate, hiding it; bip_prob was inflated 9.9% -- which carried 91.7% of the "
    "model's ENTIRE hits excess. "
    "The fitted model uses the hitter's OWN season/recent K and BB rates, which "
    "were ALREADY being fetched on every slate and handed only to the GBM. "
    "Coefficients are loaded only from the hash-bound artifact generated by "
    "scripts/fit_k_bb_final.py. Its complete fit/validation universe ends "
    f"{prov.get('fit_universe_date_max')}; out-of-sample gains are "
    f"{fits['K'].get('ll_gain'):+.1f} logL (K) and "
    f"{fits['BB'].get('ll_gain'):+.1f} (BB) over a constant. The PITCHER IS IN "
    "THE FIT, not added on top. "
    "ABSENT -> the simulator is BYTE-IDENTICAL to pre-fix."
)
pa["use_fitted_kbb"] = True
pa["kbb_artifact_path"] = "data/learning/k_bb_pre2026.json"
pa["kbb_artifact_sha256"] = artifact_sha
cfg["pa_simulator"] = pa

with cand.open("w", encoding="utf-8", newline="\n") as f:
    json.dump(cfg, f, indent=2, ensure_ascii=False)
    f.write("\n")

back = json.loads(cand.read_text(encoding="utf-8"))
orig = json.loads(live.read_text(encoding="utf-8"))
diff = sorted(k for k in set(orig) | set(back) if orig.get(k) != back.get(k))
print(f"wrote {cand}")
print(f"top-level keys differing from live: {diff}")
print(f"use_fitted_kbb = {back['pa_simulator']['use_fitted_kbb']}")
print(f"learning.apply_corrections = {back['learning']['apply_corrections']}  (must be False)")
assert diff == ["pa_simulator"], f"candidate diverges in {diff} -- expected only pa_simulator"
assert back["learning"]["apply_corrections"] is False
print("OK")
